### PR TITLE
Temp fix for Clock nullref preventing ppy:osu from running.

### PR DESCRIPTION
**Pull request by RemieRichards**

### CODE REVIEW

**Comment by peppy** [comment]
i think you missed my point. the commit i linked contains the fix.

**Comment by RemieRichards** [comment]
@peppy I can't see anything (immediately) in that commit that fixes it (though, to be fair, I don't know all of the framework), Apologies for taking your time on this.

**Comment by peppy** [comment]
trust that it does and try it out.

**Comment by RemieRichards** [comment]
@peppy Yep, that completely fixes it, no clock null refs.

**Pull request closed without merging**
